-- +goose Up
CREATE TABLE outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            UUID         NOT NULL DEFAULT gen_random_uuid(),
    aggregate_type  VARCHAR(50)  NOT NULL,
    aggregate_id    BIGINT       NOT NULL,
    event_type      VARCHAR(100) NOT NULL,
    payload         JSONB        NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'pending',
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT outbox_events_uuid_key UNIQUE (uuid),
    CONSTRAINT outbox_events_aggregate_type_chk CHECK (aggregate_type IN ('user','role','permission','product','category','brand','stock','coupon','cart','order','payment','shipment','review')),
    CONSTRAINT outbox_events_status_chk CHECK (status IN ('pending','published','failed'))
);

-- Relay worker hanya membaca event yang belum berhasil dipublish.
-- Partial index menjaga ukuran index tetap kecil meskipun tabel terus bertambah.
CREATE INDEX idx_outbox_pending
    ON outbox_events (created_at)
    WHERE status IN ('pending', 'failed');

-- BRIN cocok untuk tabel append-only yang terus bertambah.
CREATE INDEX idx_outbox_created_brin
    ON outbox_events
    USING BRIN (created_at);

-- Digunakan untuk debugging atau replay event berdasarkan aggregate.
CREATE INDEX idx_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id);

-- +goose Down
DROP TABLE IF EXISTS outbox_events;
