-- +goose Up
CREATE TABLE brands (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    slug       VARCHAR(150) NOT NULL,
    logo_url   TEXT,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT brands_uuid_key UNIQUE (uuid),
    CONSTRAINT brands_slug_key UNIQUE (slug)
);

-- +goose Down
DROP TABLE IF EXISTS brands;
