-- +goose Up
CREATE TABLE role_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID        NOT NULL DEFAULT gen_random_uuid(),
    role_id       BIGINT      NOT NULL,
    permission_id BIGINT      NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT role_permissions_uuid_key UNIQUE (uuid),
    CONSTRAINT role_permissions_role_fk  FOREIGN KEY (role_id)       REFERENCES roles (id)       ON DELETE CASCADE,
    CONSTRAINT role_permissions_perm_fk   FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_role_permissions ON role_permissions (role_id, permission_id);
CREATE INDEX idx_role_permissions_perm  ON role_permissions (permission_id);  -- untuk CASCADE delete

-- +goose Down
DROP TABLE IF EXISTS role_permissions;
