-- +goose Up
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              UUID         NOT NULL DEFAULT gen_random_uuid(),
    role_id           BIGINT       NOT NULL,
    email             VARCHAR(255) NOT NULL,
    phone             VARCHAR(30),
    password_hash     VARCHAR(255) NOT NULL,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    is_email_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at     TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT users_uuid_key UNIQUE (uuid),
    CONSTRAINT users_role_fk  FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

-- Unique partial: email boleh dipakai lagi setelah akun di-soft delete
CREATE UNIQUE INDEX uq_users_email ON users (lower(email)) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_users_phone ON users (phone) WHERE deleted_at IS NULL AND phone IS NOT NULL;

-- filter admin "user per role"
CREATE INDEX idx_users_role ON users (role_id) WHERE deleted_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS users;
