-- +goose Up
-- 1) Ubah users: password_hash jadi NULLABLE (OAuth-only user tidak punya password)
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;

-- 2) Tabel identitas login (satu user bisa punya banyak cara login)
CREATE TABLE user_identities (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    provider         VARCHAR(32)  NOT NULL,   -- 'local' | 'google' | 'facebook' | 'github' ...
    provider_user_id VARCHAR(255) NOT NULL,   -- untuk 'local' isi email; untuk oauth isi sub/id dari provider
    email            VARCHAR(255),            -- email yang dikembalikan provider (bisa beda dari users.email)
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT user_identities_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_provider_identity UNIQUE (provider, provider_user_id)
);

CREATE INDEX idx_user_identities_user ON user_identities (user_id);

-- 3) Refresh token (buat rotasi JWT — WAJIB kalau JWT access token short-lived)
CREATE TABLE refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    token_hash   VARCHAR(255) NOT NULL,       -- SHA-256 dari refresh token (JANGAN simpan plaintext)
    user_agent   VARCHAR(255),
    ip_address   INET,
    expires_at   TIMESTAMPTZ  NOT NULL,
    revoked_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT refresh_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id) WHERE revoked_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS user_identities;
ALTER TABLE users ALTER COLUMN password_hash SET NOT NULL;
