-- +goose Up
CREATE TABLE warehouses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    code       VARCHAR(50)  NOT NULL,
    address    TEXT,
    city       VARCHAR(100),
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT warehouses_uuid_key UNIQUE (uuid),
    CONSTRAINT warehouses_code_key UNIQUE (code)
);

-- +goose Down
DROP TABLE IF EXISTS warehouses;
