-- +goose Up
CREATE TABLE attributes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT attributes_uuid_key UNIQUE (uuid),
    CONSTRAINT attributes_name_key UNIQUE (name)
);

-- +goose Down
DROP TABLE IF EXISTS attributes;
