-- +goose Up
CREATE TABLE profiles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id    BIGINT       NOT NULL,
    full_name  VARCHAR(255) NOT NULL,
    gender     VARCHAR(10),
    birth_date DATE,
    avatar_url TEXT,
    bio        TEXT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT profiles_uuid_key   UNIQUE (uuid),
    CONSTRAINT profiles_user_key   UNIQUE (user_id),        -- 1:1, sekaligus index FK
    CONSTRAINT profiles_user_fk    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT profiles_gender_chk CHECK (gender IS NULL OR gender IN ('male', 'female', 'other'))
);

-- +goose Down
DROP TABLE IF EXISTS profiles;
