-- +goose Up
CREATE TABLE shipping_methods (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL DEFAULT gen_random_uuid(),
    name           VARCHAR(100) NOT NULL,
    code           VARCHAR(50)  NOT NULL,
    base_cost      BIGINT       NOT NULL DEFAULT 0,
    estimated_days VARCHAR(50),
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT shipping_methods_uuid_key UNIQUE (uuid),
    CONSTRAINT shipping_methods_code_key UNIQUE (code)
);

-- +goose Down
DROP TABLE IF EXISTS shipping_methods;
