-- +goose Up
CREATE TABLE settings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID         NOT NULL DEFAULT gen_random_uuid(),
    key         VARCHAR(150) NOT NULL,
    value       TEXT,
    description TEXT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT settings_uuid_key UNIQUE (uuid),
    CONSTRAINT settings_key_key  UNIQUE (key)
);

-- +goose Down
DROP TABLE IF EXISTS settings;
