-- +goose Up
CREATE TABLE coupons (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID        NOT NULL DEFAULT gen_random_uuid(),
    code         VARCHAR(50) NOT NULL,
    type         VARCHAR(20) NOT NULL,          -- percentage | fixed
    value        BIGINT      NOT NULL,
    min_purchase BIGINT      NOT NULL DEFAULT 0,
    max_discount BIGINT,
    quota        INTEGER,                       -- NULL = unlimited
    used_count   INTEGER     NOT NULL DEFAULT 0,
    starts_at    TIMESTAMPTZ,
    ends_at      TIMESTAMPTZ,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT coupons_uuid_key   UNIQUE (uuid),
    CONSTRAINT coupons_code_key   UNIQUE (code),
    CONSTRAINT coupons_type_check CHECK (type IN ('percentage', 'fixed')),
    CONSTRAINT coupons_period_chk CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

CREATE INDEX idx_coupons_active ON coupons (ends_at) WHERE is_active;

-- +goose Down
DROP TABLE IF EXISTS coupons;
