-- +goose Up
CREATE TABLE products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID         NOT NULL DEFAULT gen_random_uuid(),
    category_id   BIGINT       NOT NULL,
    brand_id      BIGINT,
    name          VARCHAR(255) NOT NULL,
    slug          VARCHAR(255) NOT NULL,
    description   TEXT,
    base_price    BIGINT       NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    thumbnail_url TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT products_uuid_key    UNIQUE (uuid),
    CONSTRAINT products_slug_key    UNIQUE (slug),
    CONSTRAINT products_category_fk FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT products_brand_fk    FOREIGN KEY (brand_id)    REFERENCES brands (id)     ON DELETE SET NULL,
    CONSTRAINT products_price_chk   CHECK (base_price >= 0)
);

-- Query utama katalog: filter kategori + urut terbaru, hanya produk hidup.
CREATE INDEX idx_products_category ON products (category_id, created_at DESC)
    WHERE deleted_at IS NULL AND is_active;

CREATE INDEX idx_products_brand ON products (brand_id, created_at DESC)
    WHERE deleted_at IS NULL AND is_active AND brand_id IS NOT NULL;

-- Listing "semua produk" / sort terbaru
CREATE INDEX idx_products_listing ON products (created_at DESC)
    WHERE deleted_at IS NULL AND is_active;

-- Opsional: pencarian nama produk (butuh extension pg_trgm)
-- CREATE INDEX idx_products_name_trgm ON products USING GIN (name gin_trgm_ops);

-- +goose Down
DROP TABLE IF EXISTS products;

