-- +goose Up
CREATE TABLE email_change_verifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    new_email  VARCHAR(255) NOT NULL,
    otp_hash   VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT email_change_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_email_change_active
    ON email_change_verifications (user_id)
    WHERE used_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS email_change_verifications;
