-- +goose Up
CREATE TABLE event_consumptions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID         NOT NULL DEFAULT gen_random_uuid(),
    event_id      BIGINT       NOT NULL,
    consumer_name VARCHAR(150) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'pending',
    error_message TEXT,
    processed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT event_consumptions_uuid_key UNIQUE (uuid),
    CONSTRAINT event_consumptions_event_fk FOREIGN KEY (event_id) REFERENCES outbox_events (id) ON DELETE CASCADE,
    CONSTRAINT event_consumptions_status_chk CHECK (status IN ('processing', 'success', 'failed'))
);

-- kunci idempotency: satu event hanya boleh diproses sekali per consumer.
-- Unique ini sekaligus jadi index untuk FK event_id (leading column).
CREATE UNIQUE INDEX uq_event_consumptions ON event_consumptions (event_id, consumer_name);

-- untuk retry worker
CREATE INDEX idx_event_consumptions_failed ON event_consumptions (created_at)
    WHERE status = 'failed';

-- +goose Down
DROP TABLE IF EXISTS event_consumptions;
