-- +goose Up
CREATE TABLE permissions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(150) NOT NULL,
    slug       VARCHAR(150) NOT NULL,
    module     VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT permissions_uuid_key UNIQUE (uuid),
    CONSTRAINT permissions_slug_key UNIQUE (slug)
);

CREATE INDEX idx_permissions_module ON permissions (module);

-- +goose Down
DROP TABLE IF EXISTS permissions;
