-- +goose Up
CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL DEFAULT gen_random_uuid(),
    parent_id  BIGINT,                          -- WAJIB nullable (root category)
    name       VARCHAR(150) NOT NULL,
    slug       VARCHAR(150) NOT NULL,
    icon_url   TEXT,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT categories_uuid_key   UNIQUE (uuid),
    CONSTRAINT categories_slug_key   UNIQUE (slug),
    CONSTRAINT categories_parent_fk  FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT categories_no_self    CHECK (parent_id IS DISTINCT FROM id)
);

-- untuk build tree menu; partial karena root (NULL) tidak perlu masuk index
CREATE INDEX idx_categories_parent ON categories (parent_id) WHERE parent_id IS NOT NULL;

-- +goose Down
DROP TABLE IF EXISTS categories;
